services:
  database:
    container_name: phaeroDB
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: phaerodb
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - ./initSQL.sql:/docker-entrypoint-initdb.d/initSQL.sql
      - ./../db/foodDataCSV:/foodDataCSV
      - ./../db/cleaned:/cleaned
    ports:
      - "5432:5432"

  adminer:
    image: adminer:latest
    depends_on:
      - database
    ports:
      - "8080:8080"

  python:
    container_name: phaeroFastAPI
    image: python:3.9.18-bookworm
    tty: true
    ports:
      - "7000:7000"
    volumes:
      - ../../backend/:/phaeroBackend
    working_dir: /phaeroBackend
    depends_on:
      - database
    command: bash -c "apt-get update && pip install --no-cache-dir -r requirements.txt && python create_rag_faq.py &&tail -F anything"
