version: "3.8"

services:
  app:
    build: ./frontend
    volumes:
      - ./frontend:/phaero_frontend
    working_dir: /phaero_frontend
    entrypoint: ["/bin/sh", "-c", "npm install && npm run dev"]
    ports:
      - "5173:5173" 
    container_name: phaeroFrontend


  python:
    container_name: phaeroFastAPI
    image: python:3.9.18-bookworm
    tty: true
    ports:
      - "7000:7000"
    volumes:
      - ./backend:/phaeroBackend
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    working_dir: /phaeroBackend
    command: bash -c "apt-get update && pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib && pip install --no-cache-dir -r requirements.txt  && python create_rag_faq.py && pip install gunicorn && gunicorn -w 1 -k uvicorn.workers.UvicornWorker main:app --bind 0.0.0.0:7000 --timeout 240"

  database:
    container_name: phaeroDB
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: phaerodb
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./backend/db/postgres_data:/var/lib/postgresql/data
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "5432:5432"

  adminer:
    image: adminer:latest
    depends_on:
      - database
    ports:
      - "8080:8080"

  pgbackups:
    container_name: Backup
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - ./backup:/backups
    links:
      - database:database
    depends_on:
      - database
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_DB=phaerodb
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
      - SCHEDULE=@every 12h00m00s
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=81

