export const translateExercisesToGerman = (input: string) => {
  return exercisesToGermanMapping.get(input.toLowerCase()) || input; //+ "_"; // Default to input if key is not found
};

export const translateExercisesToEnglish = (input: string) => {
  return input.split(" ").map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(" ");
};


const exercisesToGermanMapping = new Map([
  ["wrist roller", "Handgelenkroller"],
  ["wrist curl", "Handgelenkcurl"],
  ["forearm machine", "Unterarmmaschine"],
  ["stiff leg deadlift", "Stiff Leg Deadlift"],
  ["dumbbell row", "Kurzhantel-Rudern"],
  ["butterfly", "Butterfly"],
  ["reverse butterfly", "Reverse Butterfly"],
  ["bench press", "Bankdrücken"],
  ["bicep curl", "Bizepscurl"],
  ["bicep curl (barbell)", "Bizepscurl (Langhantel)"],
  ["bicep rope curl", "Bizepsseil-Curl"],
  ["calf raise", "Wadenheben"],
  ["squat", "Kniebeuge"],
  ["farmer's walk", "Farmer's Walk"],
  ["sumo deadlift", "Sumo-Kreuzheben"],
  ["deadlift", "Kreuzheben"],
  ["cable curl", "Kabelzug-Curl"],
  ["seated row", "Sitzendes Rudern"],
  ["shoulder press", "Schulterdrücken"],
  ["dumbbell bench press", "Kurzhantel-Bankdrücken"],
  ["dumbbell shoulder press", "Kurzhantel-Schulterdrücken"],
  ["romanian deadlift", "Rumänisches Kreuzheben"],
  ["leg curl", "Bein-Curl"],
  ["hamstring curl", "Hamstring-Curl"],
  ["leg extension", "Beinstrecker"],
  ["quad extension", "Quadrizeps-Strecker"],
  ["paused squat", "Pausierte Kniebeuge"],
  ["front squat", "Vorderkniebeuge"],
  ["paused bench press", "Pausiertes Bankdrücken"],
  ["paused deadlift", "Pausiertes Kreuzheben"],
  ["deficit deadlift", "Defizit-Kreuzheben"],
  ["block pull deadlift", "Block-Kreuzheben"],
  ["dumbbell curl", "Kurzhantel-Curl"],
  ["barbell curl", "Langhantel-Curl"],
  ["dip machine", "Dip-Maschine"],
  ["barbell row", "Langhantel-Rudern"],
  ["sled leg press", "Schlitten-Beinpresse"],
  ["leg press", "Beinpresse"],
  ["bent over row", "Vorgebeugtes Rudern"],
  ["skull crushers", "Skull Crushers"],
  ["cable flyes", "Kabelzug-Flyes"],
  ["cable lateral raise", "Kabelzug-Seitheben"],
  ["cable row", "Kabelzug-Rudern"],
  ["face pulls", "Face Pulls"],
  ["rear delt flyes", "Hintere-Schulter-Flyes"],
  ["incline bench press", "Schrägbankdrücken"],
  ["incline dumbbell bench press", "Schräges Kurzhantel-Bankdrücken"],
  ["incline dumbbell press", "Schräges Kurzhanteldrücken"],
  ["dips (weighted)", "Gewichtete Dips"],
  ["chin ups (weighted)", "Gewichtete Klimmzüge Untergriff"],
  ["pull ups (weighted)", "Gewichtete Klimmzüge"],
  ["push ups (weighted)", "Gewichtete Liegestütze"],
  ["lateral raise", "Seitheben"],
  ["dumbbell lateral raise", "Kurzhantel-Seitheben"],
  ["hammer curl", "Hammercurl"],
  ["preacher curl", "Predigercurl"],
  ["tricep extension", "Trizepsstrecken"],
  ["overhead tricep extension", "Überkopf-Trizepsstrecken"],
  ["tricep pushdown", "Trizepsdrücken am Kabelzug"],
  ["lat pulldown", "Latziehen"],
  ["lat pullovers", "Lat-Pullover"],
  ["running", "Laufen"],
  ["cycling", "Radfahren"],
  ["swimming", "Schwimmen"],
  ["rowing", "Rudern"],
  ["jumping rope", "Seilspringen"],
  ["walking", "Gehen"],
  ["treadmill walking", "Laufbandgehen"],
  ["treadmill running", "Laufbandlaufen"],
  ["treadmill", "Laufband"],
  ["high intensity interval training (hiit)", "Hochintensives Intervalltraining (HIIT)"],
  ["tennis", "Tennis"],
  ["soccer", "Fußball"],
  ["basketball", "Basketball"],
  ["football", "Football"],
  ["volleyball", "Volleyball"],
  ["badminton", "Badminton"],
  ["table tennis", "Tischtennis"],
  ["climbing", "Klettern"],
  ["boxing", "Boxen"],
  ["kickboxing", "Kickboxen"],
  ["wrestling", "Ringen"],
  ["dips", "Dips"],
  ["chin ups", "Klimmzüge Untergriff"],
  ["pull ups", "Klimmzüge"],
  ["push ups", "Liegestütze"],
  ["squats", "Kniebeugen"],
  ["planks", "Planken"],
  ["lunges", "Ausfallschritte"],
  ["burpees", "Burpees"],
  ["sit ups", "Sit-ups"],
  ["crunches", "Crunches"],
  ["leg raises", "Beinheben"],
  ["mountain climbers", "Bergsteiger"],
  ["russian twists", "Russische Twists"],
  ["supermans", "Supermans"],
  ["jumping jacks", "Hampelmänner"],
  ["wall sit", "Wandsitzen"],
  ["handstand pushups", "Handstand-Liegestütze"],
  ["plank to pushups", "Plank zu Liegestützen"],
  ["diamond pushups", "Diamant-Liegestütze"],
  ["front lever", "Front Lever"],
  ["skiing", "Skifahren"],
  ["ski touring", "Skitourengehen"],
  ["snowboarding", "Snowboarden"],
  ["mountain biking", "Mountainbiken"],
  ["mountain hiking", "Bergwandern"],
]);
