"""exercise table changes



Revision ID: a58272c57e07
Revises: 938e0250be56
Create Date: 2024-01-26 12:30:16.793817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a58272c57e07"
down_revision: Union[str, None] = "938e0250be56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add new column (nullable temporarily)
    op.add_column("exercises", sa.Column("exercise_type", sa.String(), nullable=True))

    # Execute raw SQL for data migration
    conn = op.get_bind()
    conn.execute(sa.text("UPDATE exercises SET exercise_type = weight_or_cardio"))

    # Change new column to non-nullable
    op.alter_column("exercises", "exercise_type", nullable=False)

    # Continue with other operations
    op.drop_index("ix_exercises_weight_or_cardio", table_name="exercises")
    op.create_index(
        op.f("ix_exercises_exercise_type"), "exercises", ["exercise_type"], unique=False
    )
    op.drop_column("exercises", "weight_or_cardio")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "exercises",
        sa.Column(
            "weight_or_cardio", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.drop_index(op.f("ix_exercises_exercise_type"), table_name="exercises")
    op.create_index(
        "ix_exercises_weight_or_cardio", "exercises", ["weight_or_cardio"], unique=False
    )
    op.drop_column("exercises", "exercise_type")
    # ### end Alembic commands ###
