"""new columns for wellbeing and so on

Revision ID: f4583e960a24
Revises: a58272c57e07
Create Date: 2024-01-27 08:28:31.078795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f4583e960a24"
down_revision: Union[str, None] = "a58272c57e07"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "exercisedata",
        sa.Column("computed_activity_level", sa.Integer(), nullable=True),
    )
    op.add_column(
        "notedata", sa.Column("computed_wellbeing_score", sa.Integer(), nullable=True)
    )
    op.add_column(
        "sleepdata", sa.Column("computed_sleep_quality", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sleepdata", "computed_sleep_quality")
    op.drop_column("notedata", "computed_wellbeing_score")
    op.drop_column("exercisedata", "computed_activity_level")
    # ### end Alembic commands ###
